#!/bin/bash

if [ ! -d "$HOME/Logs/" ] ; then
    mkdir $HOME/Logs/
fi

ts=`date +%b_%a_%d_%Y_%H:%M`

suecard=$(aplay -l|grep s1000|awk -F ":" '{print $1}'|sed -e 's/card //')
if [[ "$suecard" == "" ]]
then
	echo "Could not find SueCreek harware!!"
	aplay -l
	exit -1
fi
hw_name="hw:$suecard"

cd [AVSROOT]/sdk-build/SampleApp/src
TZ=UTC ./SampleApp [AVSROOT]/sdk-build/Integration/AlexaClientSDKConfig.json DEBUG9 $hw_name 2>$HOME/Logs/${ts}_stderr.log | tee $HOME/Logs/${ts}_stdout.log



